name: ccc
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.2.*
  - cupy=13.2.*
  - ipython=7.*
  - ipywidgets
  - jupyterlab=3.3.*
  - jupytext=1.11.*
  - matplotlib=3.4.*
  - minepy=1.2.*
  - numba=0.60.*
  - numpy=1.25.*
  - openpyxl=3.0.*
  - pandas=1.3.*
  - papermill=2.3.*
  - pip
  - pytables=3.7.*
  - pytest=6.*
  - python=3.9.*
  - pyyaml=5.4.*
  - requests=2.*
  - r-base=4.1.*
  - r-devtools
  - r-essentials
  - r-reticulate=1.*
  - r-svglite=2.*
  - rpy2=3.4.*
  - scikit-learn=0.24.*
  - scipy=1.9.*
  - seaborn=0.11.*
  - svgutils=0.3.*
  - tabulate=0.8.*
  - tqdm=4.*
  - upsetplot=0.6.*
